<template>
  <q-page>
    <h5 class="q-mt-none">Ajuda</h5>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi elit, vehicula a tellus eu, commodo condimentum nibh. Vestibulum eget sodales purus. Vivamus nibh mi, dignissim sed urna ac, posuere tincidunt metus. Nunc sit amet ex condimentum, congue orci vitae, iaculis magna. Aliquam nec diam at turpis cursus euismod id eget elit. Ut lobortis egestas ullamcorper. Integer viverra vulputate dui nec aliquam. Quisque ultrices enim in fermentum placerat. Cras id tellus lacinia, dignissim arcu ac, porta mi. Donec euismod faucibus libero, in tempor dui. Donec eu vestibulum dui. Curabitur ultricies euismod augue nec tempus. Nam sit amet placerat quam, id pharetra est. Praesent eu aliquam lacus, vitae ultrices mauris.</p>
    <p>Proin imperdiet diam mi, vel fermentum elit sodales eu. Integer aliquet rhoncus dui id luctus. Maecenas malesuada, quam ut semper condimentum, nisl leo aliquet magna, non venenatis nisi risus at elit. Vestibulum id purus eu nibh dictum ornare nec non tellus. Donec massa sapien, consequat quis leo a, rhoncus maximus eros. Donec dictum neque eu purus venenatis, ultricies malesuada libero dictum. Pellentesque euismod non odio non malesuada. Etiam maximus nibh consectetur vulputate dignissim. Ut purus magna, rhoncus eu fermentum a, pellentesque ut turpis. Sed tristique ligula at velit sollicitudin, in lacinia felis euismod. Cras tristique tempor nunc eget fringilla. Sed et nisl nulla. Cras tempor, sem eget egestas malesuada, nisl ipsum auctor sem, ut dapibus lorem nibh non erat. Phasellus tempus est felis. Mauris iaculis, magna a pulvinar condimentum, lacus justo posuere risus, nec laoreet dolor urna vitae turpis.</p>
    <p>Curabitur imperdiet erat lorem, vitae dapibus erat convallis a. Etiam scelerisque lacinia sapien, vitae euismod libero ultrices sed. Nam rutrum purus sed luctus tempor. Etiam interdum, nunc ornare tristique ultrices, neque velit aliquam nulla, eu vehicula nulla risus ac felis. Aenean efficitur dolor quis pharetra viverra. Pellentesque sit amet sapien velit. Nam placerat arcu nec sem commodo, vitae facilisis erat convallis. Cras leo velit, finibus et velit vel, hendrerit elementum dui. Vestibulum efficitur neque urna, luctus suscipit turpis suscipit vel. Sed tempus dictum nisi in varius.</p>
    <p>Sed nisl dolor, vehicula ullamcorper tincidunt nec, placerat non metus. Vestibulum id ullamcorper elit, porta fermentum orci. Curabitur non arcu a elit bibendum feugiat eget sit amet sapien. Nunc fermentum orci quis elit viverra, sit amet fermentum eros condimentum. Praesent eget mauris in dolor viverra venenatis eget ut neque. Suspendisse quis quam ex. Vivamus non tellus maximus, viverra nulla at, faucibus odio. Duis a est dui. Donec vel vehicula augue, nec lacinia velit. Donec pretium a neque id tempus. Nullam sit amet tincidunt arcu.</p>
    <p>In interdum ac tellus ac accumsan. Praesent nec imperdiet tellus. Nam augue augue, efficitur id auctor et, dapibus vel justo. Fusce mattis aliquam lacus. Praesent congue placerat sapien accumsan porttitor. Praesent imperdiet lacus nunc, nec fermentum urna laoreet sit amet. Vivamus id placerat tellus.</p>
  </q-page>
</template>

<script>
export default {
}
</script>
